/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PositionsOrdersRouteImport } from './routes/positions-orders'
import { Route as TradeHistoryRouteImport } from './routes/trade-history'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsOrdersRoute = PositionsOrdersRouteImport.update({
  id: '/positions-orders',
  path: '/positions-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeHistoryRoute = TradeHistoryRouteImport.update({
  id: '/trade-history',
  path: '/trade-history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/portfolio': typeof PortfolioRoute
  '/positions-orders': typeof PositionsOrdersRoute
  '/trade-history': typeof TradeHistoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/portfolio': typeof PortfolioRoute
  '/positions-orders': typeof PositionsOrdersRoute
  '/trade-history': typeof TradeHistoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/journal': typeof JournalRoute
  '/portfolio': typeof PortfolioRoute
  '/positions-orders': typeof PositionsOrdersRoute
  '/trade-history': typeof TradeHistoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/journal' | '/portfolio' | '/positions-orders' | '/trade-history'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/journal' | '/portfolio' | '/positions-orders' | '/trade-history'
  id:
    | '__root__'
    | '/'
    | '/journal'
    | '/portfolio'
    | '/positions-orders'
    | '/trade-history'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JournalRoute: typeof JournalRoute
  PortfolioRoute: typeof PortfolioRoute
  PositionsOrdersRoute: typeof PositionsOrdersRoute
  TradeHistoryRoute: typeof TradeHistoryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions-orders': {
      id: '/positions-orders'
      path: '/positions-orders'
      fullPath: '/positions-orders'
      preLoaderRoute: typeof PositionsOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade-history': {
      id: '/trade-history'
      path: '/trade-history'
      fullPath: '/trade-history'
      preLoaderRoute: typeof TradeHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JournalRoute: JournalRoute,
  PortfolioRoute: PortfolioRoute,
  PositionsOrdersRoute: PositionsOrdersRoute,
  TradeHistoryRoute: TradeHistoryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
